"""edited individual columns

Revision ID: bba3fba51a55
Revises: d13d93396bc2
Create Date: 2024-08-28 09:46:39.556612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba3fba51a55'
down_revision = 'd13d93396bc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individuals', sa.Column('user_id', sa.String(length=45), nullable=False))
    op.drop_constraint('individuals_created_by_fkey', 'individuals', type_='foreignkey')
    op.create_foreign_key(None, 'individuals', 'users', ['user_id'], ['uuid'])
    op.drop_column('individuals', 'password_hash')
    op.drop_column('individuals', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individuals', sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('individuals', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'individuals', type_='foreignkey')
    op.create_foreign_key('individuals_created_by_fkey', 'individuals', 'users', ['created_by'], ['uuid'])
    op.drop_column('individuals', 'user_id')
    # ### end Alembic commands ###
