"""remove created_by and BaseModelMixin

Revision ID: 4d4a6b91277b
Revises: 4173135859bf
Create Date: 2024-08-27 08:37:33.925926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4a6b91277b'
down_revision = '4173135859bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('individuals_created_by_fkey', 'individuals', type_='foreignkey')
    op.drop_column('individuals', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individuals', sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key('individuals_created_by_fkey', 'individuals', 'users', ['created_by'], ['uuid'])
    # ### end Alembic commands ###
