"""added address to the corporate table

Revision ID: 9c8150fb6f1f
Revises: 968b236ccc6d
Create Date: 2024-09-12 11:08:57.260643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8150fb6f1f'
down_revision = '968b236ccc6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporates', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporates', 'address')
    # ### end Alembic commands ###
