"""removed creator from individual

Revision ID: 337ae1ad721d
Revises: 4aa2ebdd8e6f
Create Date: 2024-08-26 21:46:19.672364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337ae1ad721d'
down_revision = '4aa2ebdd8e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
