"""employee and employer relationship

Revision ID: 6e10ffef6f98
Revises: 385c278e50fe
Create Date: 2024-09-10 10:58:24.704358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e10ffef6f98'
down_revision = '385c278e50fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
