"""edited individual columns (removed user like fields)

Revision ID: c8d3a921e0da
Revises: bba3fba51a55
Create Date: 2024-08-28 10:07:31.985664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d3a921e0da'
down_revision = 'bba3fba51a55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('individuals_email_key', 'individuals', type_='unique')
    op.drop_column('individuals', 'firstname')
    op.drop_column('individuals', 'middlename')
    op.drop_column('individuals', 'phone')
    op.drop_column('individuals', 'email')
    op.drop_column('individuals', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individuals', sa.Column('lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('individuals', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('individuals', sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('individuals', sa.Column('middlename', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('individuals', sa.Column('firstname', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('individuals_email_key', 'individuals', ['email'])
    # ### end Alembic commands ###
