"""removed unique on ClassRoom and Subject

Revision ID: 968b236ccc6d
Revises: 8937da66b4a0
Create Date: 2024-09-12 09:27:27.682589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968b236ccc6d'
down_revision = '8937da66b4a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classes_name_key', 'classes', type_='unique')
    op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
    op.create_unique_constraint('classes_name_key', 'classes', ['name'])
    # ### end Alembic commands ###
