"""added nullable to private_and_corporate relationship

Revision ID: 5a11758ebbd1
Revises: 595ed4109aca
Create Date: 2024-09-12 12:15:20.198806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a11758ebbd1'
down_revision = '595ed4109aca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
