"""added country

Revision ID: 679fadfc4b97
Revises: 
Create Date: 2024-09-02 19:20:27.476410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679fadfc4b97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_groups_created_at'), 'groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_groups_date'), 'groups', ['date'], unique=False)
    op.create_table('passwordresets',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_passwordresets_created_at'), 'passwordresets', ['created_at'], unique=False)
    op.create_index(op.f('ix_passwordresets_date'), 'passwordresets', ['date'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_permissions_date'), 'permissions', ['date'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_date'), 'roles', ['date'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('old_password_hash', sa.String(length=255), nullable=True),
    sa.Column('temp_password_hash', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('middlename', sa.String(length=255), nullable=True),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('can_login', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_temp_email', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_temp_phone', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_date'), 'users', ['date'], unique=False)
    op.create_table('countries',
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_countries_created_at'), 'countries', ['created_at'], unique=False)
    op.create_index(op.f('ix_countries_date'), 'countries', ['date'], unique=False)
    op.create_table('permission_role',
    sa.Column('permission_id', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.uuid'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.uuid'], )
    )
    op.create_table('role_group',
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.uuid'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.uuid'], )
    )
    op.create_table('user_group',
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], )
    )
    op.create_table('states',
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('country_id', sa.String(length=45), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.uuid'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_states_created_at'), 'states', ['created_at'], unique=False)
    op.create_index(op.f('ix_states_date'), 'states', ['date'], unique=False)
    op.create_table('localgovernments',
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('state_id', sa.String(length=45), nullable=False),
    sa.Column('display_name', sa.String(length=45), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_localgovernments_created_at'), 'localgovernments', ['created_at'], unique=False)
    op.create_index(op.f('ix_localgovernments_date'), 'localgovernments', ['date'], unique=False)
    op.create_table('individuals',
    sa.Column('user_id', sa.String(length=45), nullable=False),
    sa.Column('state_id', sa.String(length=45), nullable=True),
    sa.Column('lga_id', sa.String(length=45), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.String(length=45), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('account_type', sa.String(length=100), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lga_id'], ['localgovernments.uuid'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_individuals_created_at'), 'individuals', ['created_at'], unique=False)
    op.create_index(op.f('ix_individuals_date'), 'individuals', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individuals_date'), table_name='individuals')
    op.drop_index(op.f('ix_individuals_created_at'), table_name='individuals')
    op.drop_table('individuals')
    op.drop_index(op.f('ix_localgovernments_date'), table_name='localgovernments')
    op.drop_index(op.f('ix_localgovernments_created_at'), table_name='localgovernments')
    op.drop_table('localgovernments')
    op.drop_index(op.f('ix_states_date'), table_name='states')
    op.drop_index(op.f('ix_states_created_at'), table_name='states')
    op.drop_table('states')
    op.drop_table('user_group')
    op.drop_table('role_group')
    op.drop_table('permission_role')
    op.drop_index(op.f('ix_countries_date'), table_name='countries')
    op.drop_index(op.f('ix_countries_created_at'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_users_date'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_date'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_date'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_passwordresets_date'), table_name='passwordresets')
    op.drop_index(op.f('ix_passwordresets_created_at'), table_name='passwordresets')
    op.drop_table('passwordresets')
    op.drop_index(op.f('ix_groups_date'), table_name='groups')
    op.drop_index(op.f('ix_groups_created_at'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
