"""added created_by

Revision ID: 4173135859bf
Revises: 337ae1ad721d
Create Date: 2024-08-27 08:32:40.463809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4173135859bf'
down_revision = '337ae1ad721d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
