"""removed contact unique

Revision ID: f8c30995d6e0
Revises: 5a11758ebbd1
Create Date: 2024-09-12 12:22:13.097292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c30995d6e0'
down_revision = '5a11758ebbd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('corporates_head_contact_key', 'corporates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('corporates_head_contact_key', 'corporates', ['head_contact'])
    # ### end Alembic commands ###
