"""added corporate and relationship

Revision ID: a119f9c242d5
Revises: 78c5b94bf47a
Create Date: 2024-09-10 10:26:33.105717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a119f9c242d5'
down_revision = '78c5b94bf47a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_corporate',
    sa.Column('individual_id', sa.String(length=50), nullable=True),
    sa.Column('corporate_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.uuid'], ),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.uuid'], )
    )
    op.add_column('corporates', sa.Column('country_id', sa.String(length=45), nullable=True))
    op.add_column('corporates', sa.Column('state_id', sa.String(length=45), nullable=True))
    op.add_column('corporates', sa.Column('lga_id', sa.String(length=45), nullable=True))
    op.add_column('corporates', sa.Column('delivery_level', sa.String(length=255), nullable=True))
    op.add_column('corporates', sa.Column('secondary_contacts', sa.String(length=255), nullable=True))
    op.add_column('corporates', sa.Column('head', sa.String(length=255), nullable=True))
    op.add_column('corporates', sa.Column('head_contact', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'corporates', ['head_contact'])
    op.create_foreign_key(None, 'corporates', 'states', ['state_id'], ['uuid'])
    op.create_foreign_key(None, 'corporates', 'countries', ['country_id'], ['uuid'])
    op.create_foreign_key(None, 'corporates', 'localgovernments', ['lga_id'], ['uuid'])
    op.drop_column('individuals', 'institution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individuals', sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'corporates', type_='foreignkey')
    op.drop_constraint(None, 'corporates', type_='foreignkey')
    op.drop_constraint(None, 'corporates', type_='foreignkey')
    op.drop_constraint(None, 'corporates', type_='unique')
    op.drop_column('corporates', 'head_contact')
    op.drop_column('corporates', 'head')
    op.drop_column('corporates', 'secondary_contacts')
    op.drop_column('corporates', 'delivery_level')
    op.drop_column('corporates', 'lga_id')
    op.drop_column('corporates', 'state_id')
    op.drop_column('corporates', 'country_id')
    op.drop_table('individual_corporate')
    # ### end Alembic commands ###
