"""employee and employer relationships

Revision ID: 8937da66b4a0
Revises: 6e10ffef6f98
Create Date: 2024-09-10 10:59:31.134597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8937da66b4a0'
down_revision = '6e10ffef6f98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
