"""added institution back to individual

Revision ID: 385c278e50fe
Revises: a119f9c242d5
Create Date: 2024-09-10 10:32:52.067256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385c278e50fe'
down_revision = 'a119f9c242d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individuals', sa.Column('institution', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individuals', 'institution')
    # ### end Alembic commands ###
