"""added individual model

Revision ID: 4aa2ebdd8e6f
Revises: ebfb015578f7
Create Date: 2024-08-26 20:58:50.446747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aa2ebdd8e6f'
down_revision = 'ebfb015578f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individuals',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('middlename', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('state_id', sa.String(length=45), nullable=True),
    sa.Column('lga_id', sa.String(length=45), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.String(length=45), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('account_type', sa.String(length=100), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['lga_id'], ['localgovernments.uuid'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_individuals_created_at'), 'individuals', ['created_at'], unique=False)
    op.create_index(op.f('ix_individuals_date'), 'individuals', ['date'], unique=False)
    op.drop_index('ix_profiles_created_at', table_name='profiles')
    op.drop_index('ix_profiles_date', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('state_id', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('lga_id', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], name='profiles_created_by_fkey'),
    sa.ForeignKeyConstraint(['lga_id'], ['localgovernments.uuid'], name='profiles_lga_id_fkey'),
    sa.ForeignKeyConstraint(['state_id'], ['states.uuid'], name='profiles_state_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name='profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey'),
    sa.UniqueConstraint('uuid', name='profiles_uuid_key')
    )
    op.create_index('ix_profiles_date', 'profiles', ['date'], unique=False)
    op.create_index('ix_profiles_created_at', 'profiles', ['created_at'], unique=False)
    op.drop_index(op.f('ix_individuals_date'), table_name='individuals')
    op.drop_index(op.f('ix_individuals_created_at'), table_name='individuals')
    op.drop_table('individuals')
    # ### end Alembic commands ###
