"""change dob to nullable

Revision ID: 595ed4109aca
Revises: 9c8150fb6f1f
Create Date: 2024-09-12 11:19:05.145028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595ed4109aca'
down_revision = '9c8150fb6f1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('individuals', 'date_of_birth',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('individuals', 'date_of_birth',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###
