#!/usr/bin/env python
# -=-<[ Bismillahirrahmanirrahim ]>-=-
# -*- coding: utf-8 -*-
# @Date    : 2021-05-08 18:05:48
# @Author  : Dahir Muhammad Dahir
# @Description : something cool


from enum import Enum


class ActionStatus(str, Enum):
    success = "success"
    failed = "failed"


class Gender(str, Enum):
    male = "m"
    female = "f"
    na = "NA"


class FileFormat(str, Enum):
    pdf = ".pdf"
    excel = ".xlsx"
    csv = ".csv"
    json = ".json"
    xml = ".xml"


class LicenseValidity(str, Enum):
    valid = "valid"
    expired = "expired"


class UserStatus(str, Enum):
    enabled = "enabled"
    disabled = "disabled"


class AlumniVisibility(str, Enum):
    public = "public"  # visible to everyone
    private = "private"  # visible to only the user and admin
    recruiters = "recruiters"  # visible to only recruiters and admin
    class_members = "class_members"  # visible to only class members


class AlumniProfileStatus(str, Enum):
    claimed = "claimed"
    unclaimed = "unclaimed"


class AlumniRequestStatus(str, Enum):
    pending = "pending"
    approved = "approved"
    rejected = "rejected"


class JobType(str, Enum):
    full_time = "full_time"
    part_time = "part_time"
    contract = "contract"
    internship = "internship"


class JobApplicationStatus(str, Enum):
    applied = "applied"
    processing = "processing"
    accepted = "accepted"
    rejected = "rejected"


class NINType(str, Enum):
    national = "national"
    autogenerated = "autogenerated"


class WalletStatus(str, Enum):
    enabled = "enabled"
    disabled = "disabled"
    closed = "closed"
